# Generated by Django 5.2.7 on 2025-10-10 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_genre_subscription_delete_genres_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genre',
            old_name='genres',
            new_name='genre',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='genres',
            new_name='genre',
        ),
    ]
