# Generated by Django 5.2.7 on 2025-10-10 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0003_rename_genres_genre_genre_rename_genres_movie_genre'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Genre',
            new_name='Genres',
        ),
        migrations.RenameModel(
            old_name='Movie',
            new_name='Movies',
        ),
        migrations.RenameModel(
            old_name='Payment',
            new_name='Payments',
        ),
        migrations.RenameModel(
            old_name='Subscription',
            new_name='Subscriptions',
        ),
        migrations.AlterField(
            model_name='watchhistory',
            name='rating',
            field=models.IntegerField(blank=True, choices=[(1, '1 star'), (2, '2 stars'), (3, '3 stars'), (4, '4 stars'), (5, '5 stars')], null=True),
        ),
    ]
